
spring:

  application:
    name: hospital-sgch-backend
  

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/hospital-sgch}  # URL por defecto, o lee de una variable DB_URL
    username: ${DB_USERNAME:usuario_default}                        # Lee de DB_USERNAME, si no existe usa 'usuario_default'
    password: ${DB_PASSWORD:password_default}                        # Lee de DB_PASSWORD, si no existe usa 'password_default'
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update